name: ${project.name}
main: net.enelson.sopafterworld.SopAfterworld
version: ${project.version}
authors: [E_NeLsOn]
depend: [SopLib, PlaceholderAPI]
api-version: 1.16
commands:
  sopafterworld:
    aliases: [afterworld, totalafterworld]
  portal:
    aliases: []
